# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.withdraw_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.withdraw_btn.setGeometry(QtCore.QRect(30, 270, 81, 26))
        self.withdraw_btn.setObjectName("withdraw_btn")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 30, 71, 16))
        self.label.setObjectName("label")
        self.deposit_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.deposit_btn.setGeometry(QtCore.QRect(140, 270, 71, 26))
        self.deposit_btn.setObjectName("deposit_btn")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(18, 60, 101, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 101, 16))
        self.label_3.setObjectName("label_3")
        self.first_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.first_name.setGeometry(QtCore.QRect(140, 60, 113, 21))
        self.first_name.setObjectName("first_name")
        self.last_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.last_name.setGeometry(QtCore.QRect(140, 120, 113, 21))
        self.last_name.setObjectName("last_name")
        self.amount = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.amount.setGeometry(QtCore.QRect(130, 200, 113, 21))
        self.amount.setObjectName("amount")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 200, 81, 20))
        self.label_4.setObjectName("label_4")
        self.acct_bal = QtWidgets.QLabel(parent=self.centralwidget)
        self.acct_bal.setGeometry(QtCore.QRect(60, 320, 231, 41))
        self.acct_bal.setObjectName("acct_bal")
        self.search_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.search_btn.setGeometry(QtCore.QRect(84, 160, 81, 21))
        self.search_btn.setObjectName("search_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ATM"))
        self.withdraw_btn.setText(_translate("MainWindow", "Withdraw"))
        self.label.setText(_translate("MainWindow", "Bank ATM "))
        self.deposit_btn.setText(_translate("MainWindow", "Deposit"))
        self.label_2.setText(_translate("MainWindow", "First Name"))
        self.label_3.setText(_translate("MainWindow", "Last Name"))
        self.label_4.setText(_translate("MainWindow", "Enter Amount"))
        self.acct_bal.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.search_btn.setText(_translate("MainWindow", "Search"))
